<a href="https://colab.research.google.com/github/vannagrimaldo/Python-Foundations/blob/main/Week2_Numpy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

An array is a data structure that stores values of same data type
A list can save values of any kind, but an array can only store values of the same data type.
Arrays are more performative when computing large sets of numerical data so we use numpy arrays.


##2.1 NumPy Arrays

In [2]:
arr_str= ['Mercedes','BMW','Audi','Ferrari','Tesla']
arr_num= ['1','2','3','4','5']
# these can be converted to numpy arrays
np_arr_str= np.array(arr_str)
np_arr_num= np.array(arr_num)

print(np_arr_num)
print(np_arr_str)

print(type(arr_num))
print(type(arr_str))

#lets print to make sure we converted them to arrays properly
print('Data type of arr_num: ', type(np_arr_num))
print('Data type of arr_str: ', type(np_arr_str))

#lastly lets talk about matrixes,
#a matrix is a two dimensional list data structure where elements are arranged into rows and columns
matirx= np.array ([[1,2,3],[2,3,4],[3,4,5]])
print(matirx)
print(type(matirx))

['1' '2' '3' '4' '5']
['Mercedes' 'BMW' 'Audi' 'Ferrari' 'Tesla']
<class 'list'>
<class 'list'>
Data type of arr_num:  <class 'numpy.ndarray'>
Data type of arr_str:  <class 'numpy.ndarray'>
[[1 2 3]
 [2 3 4]
 [3 4 5]]
<class 'numpy.ndarray'>


##2.2 NumPy Functions Part 1

the **np.arange function**, it returns an array with the specified start and stop and maybe intervals if selected also.
Remember in python the end is always excluded.

Using np.arange() function

The np.arange() function returns an array with evenly spaced elements as per the interval. The interval mentioned is half-opened i.e. start is included but stop is excluded.
It has the following paramaters:
start : start of interval range. By default start = 0
stop : end of interval range
step : step size of interval. By default step size = 1

In [3]:

arr2 = np.arange(start= 0, stop= 10)
print(arr2)
arr3 = np.arange(start= 0, stop= 10, step=2)
print(arr3)


[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


**np.linspace() function**
the np.linspace returns numpers that are evenly distributed with respect to interval, here the start and stop are both included, and the default numb of spaces is 50

In [4]:
matrix2= np.linspace(0,100)
print(matrix2)

matrix3= np.linspace(0,1000,10)    #  defining tha amount of steps

print(matrix3)

vec = np.linspace(10,20,3)
print(vec)
vec = np.zeros([2,3])
print(vec)

[  0.           2.04081633   4.08163265   6.12244898   8.16326531
  10.20408163  12.24489796  14.28571429  16.32653061  18.36734694
  20.40816327  22.44897959  24.48979592  26.53061224  28.57142857
  30.6122449   32.65306122  34.69387755  36.73469388  38.7755102
  40.81632653  42.85714286  44.89795918  46.93877551  48.97959184
  51.02040816  53.06122449  55.10204082  57.14285714  59.18367347
  61.2244898   63.26530612  65.30612245  67.34693878  69.3877551
  71.42857143  73.46938776  75.51020408  77.55102041  79.59183673
  81.63265306  83.67346939  85.71428571  87.75510204  89.79591837
  91.83673469  93.87755102  95.91836735  97.95918367 100.        ]
[   0.          111.11111111  222.22222222  333.33333333  444.44444444
  555.55555556  666.66666667  777.77777778  888.88888889 1000.        ]
[10. 15. 20.]
[[0. 0. 0.]
 [0. 0. 0.]]




**Using np.zeros()**

* The np.zeros() is a function for creating a matrix and performing matrix operations in NumPy.
* It returns a matrix filled with zeros of the given shape.
* It has the following parameters:    
  * shape : Number of rows and columns in the output matrix.
  * dtype: data type of the elements in the matrix, by default the value is set to `float`.

In [5]:
matrix4=np.zeros([3,5])
print(matrix4)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


**the np.ones() function**
 creates and returns a matrix filled with ones

In [6]:
matrix5=np.ones([3,5])
print(matrix5)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


**Using np.eye()**
* The np.eye() is a function for creating a matrix and performing matrix operations in NumPy.
* It returns a matrix with ones on the diagonal and zeros elsewhere.
* It has the following parameters:
  * n: Number of rows and columns in the output matrix
  * dtype: data type of the elements in the matrix, by default the value is set to `float`.


In [7]:
matrix6 = np.eye(5)
print(matrix6)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


##2.3 Numpy Function Part 2

We can create a one dimension array to a  matri. This can be done by using
**the np.reshape()**
syntax is : array.reshape(shape)

* The shape of an array basically tells the number of elements and dimensions of the array. Reshaping a Numpy array simply means changing the shape of the given array.
* By reshaping an array we can add or remove dimensions or change number of elements in each dimension.
* In order to reshape a NumPy array, we use the reshape method with the given array.
* **Syntax:** array.reshape(shape)
  * shape: a tuple given as input, the values in tuple will be the new shape of the array.

In [8]:
arr4 = np.arange(0,10)
arr4
arr4_reshaped= arr4.reshape((2,5))
arr4_reshaped
#make sure the dimension works with the amount of elements you have.

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Numpy also has
1.trigonometric functions
2.Exponent and logarithmic functions
3.functions for arithmetic ops between arrays and matrices


In [9]:
print(np.sin(4))
print(np.cos(4))
print(np.tan(4))

print(np.exp(2))
print(np.log(2))

arr5=np.array([2,4,6])
print(np.log(arr5)) #log base is usually 0

print(np.log10(arr5))

-0.7568024953079282
-0.6536436208636119
1.1578212823495775
7.38905609893065
0.6931471805599453
[0.69314718 1.38629436 1.79175947]
[0.30103    0.60205999 0.77815125]


##2.4 Numpy Functions Part 3


**Arithmetic Functions**

In [10]:
# this is just all about the operations on list, arrays, and matrices
l1=[1,2,3]
l2=[4,5,6]
print (l1+l2)# doesn't work like how we'd like it

arr7= np.arange(1,6)
arr8= np.arange(3,8)

print(arr7)
print(arr8)

#illustration operations on arrays
print('Addition : ', arr7+arr8)
print('Subraction : ', arr7-arr8)
print('Multiplication : ', arr7*arr8)
print('Division : ', arr7/arr8)
print('Inverse : ', 1/arr7)
print('Power : ', arr7**arr8)

matrix7 = np.arange(1,10).reshape(3,3)
matrix8 = np.eye(3)
print(matrix7)
print(matrix8)

#illustratin operations on matrices
print('Addition: \n',matrix7+matrix8)
print('Subraction: \n',matrix7-matrix8)
print('Multiplication: \n',matrix7*matrix8)
print('Division: \n',matrix7/matrix8)




#linear algrabra matrix multiplication
matrix9= np.arange(1,10).reshape(3,3)
print(matrix9)

matrix10=np.arange(11,20).reshape(3,3)
print(matrix10)

#for the linear algebra multiplication some may have heard this as (linear algebra dot product)
print('Multiplicaton: \n' ,matrix9 @ matrix10)
print(np.transpose(matrix9))
print(matrix9.T)



[1, 2, 3, 4, 5, 6]
[1 2 3 4 5]
[3 4 5 6 7]
Addition :  [ 4  6  8 10 12]
Subraction :  [-2 -2 -2 -2 -2]
Multiplication :  [ 3  8 15 24 35]
Division :  [0.33333333 0.5        0.6        0.66666667 0.71428571]
Inverse :  [1.         0.5        0.33333333 0.25       0.2       ]
Power :  [    1    16   243  4096 78125]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Addition: 
 [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
Subraction: 
 [[0. 2. 3.]
 [4. 4. 6.]
 [7. 8. 8.]]
Multiplication: 
 [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
Division: 
 [[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
Multiplicaton: 
 [[ 90  96 102]
 [216 231 246]
 [342 366 390]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


<ipython-input-10-eb36fe806d8b>:29: RuntimeWarning: divide by zero encountered in divide
  print('Division: \n',matrix7/matrix8)


##2.5 Numpy Fuctions Part 4

**Matrix Operations**

In [11]:
#find min / max values of matrix
print('Min value: ', np.min(matrix9))
print('Max value: ', np.max(matrix9))

#function to generate random samples
#draws randomly from the normal distribution with a mean of 0 and std dev of 1

print(np.random.rand(5))
rand_mat=np.random.rand(5,5)
print(rand_mat)
print(np.mean(rand_mat))
print(np.std(rand_mat))

rand_mat3 = np.random.randint(1,5,10)# for an array
print(rand_mat3)


rand_mat3 = np.random.randint(1,10,[5,5])#for a matrix
print(rand_mat3)



Min value:  1
Max value:  9
[0.79000484 0.66302716 0.88247756 0.90058017 0.60038794]
[[0.36793775 0.3363465  0.32780745 0.48595317 0.3656161 ]
 [0.57028018 0.40296781 0.80582069 0.93603033 0.08283151]
 [0.70588767 0.4496711  0.52476005 0.5378737  0.69656077]
 [0.12752943 0.41665183 0.97529948 0.8167709  0.49561531]
 [0.44056398 0.01326938 0.41944005 0.41553531 0.16994249]]
0.47547851759370574
0.24246166675285222
[1 4 2 2 3 3 4 2 3 4]
[[6 1 3 3 2]
 [8 6 4 5 3]
 [8 2 9 9 4]
 [3 6 9 1 4]
 [5 8 6 9 6]]


##2.6 Accessing Entries of a NumPy Array

In [12]:
#generate an array with 10 random values
rand_arr= np.random.randn(10)
print(rand_arr)

#accessing an element of an array- same as accessing lists and tuples
print(rand_arr[6])


#accessing multiple elements from an array
print(rand_arr[4:9])

#accessing multiple non consecutive entries using np.arange
print('Index of values to access: ', np.arange(3,10,3) )
print(rand_arr[np.arange(3,10,3)])


#accessing values using logical operations
#>0
print('Values greater than 0', rand_arr[rand_arr>0])
#<0
print('Values less than 0', rand_arr[rand_arr<0])


#ACCESSING MATRICES

rand_mat= np.random.randn(5,5)
print(rand_mat)

#accessing a row
print(rand_mat[1])
#accessing a specific value
print(rand_mat[1,2])
print(rand_mat[1][2]) #both ways work

#accessing specific rows and columns
print(rand_mat[0:2, 1:3]) #remember last number not included.

#using logical operations

print('Values greater than 0', rand_mat[rand_mat>0]) #abandons matrix and creates a list.
print('Values less than than 0', rand_mat[rand_mat<0])

#modify int the entries of an array

rand_arr[3:5]=5
print(rand_arr)

rand_arr[3:5]=[2,3]
print(rand_arr)


rand_arr[rand_arr>0]=65
print(rand_arr)

vec1 = np.array([4, 7, 8, 9, 10, 6, 1])
vec1[vec1>6] = 2
print(vec1)



[ 1.55462243  0.24704729 -0.86027963 -2.15971501  0.52196655  0.72715142
  0.7079987  -0.01548878 -2.09324223 -0.52046181]
0.7079986989464744
[ 0.52196655  0.72715142  0.7079987  -0.01548878 -2.09324223]
Index of values to access:  [3 6 9]
[-2.15971501  0.7079987  -0.52046181]
Values greater than 0 [1.55462243 0.24704729 0.52196655 0.72715142 0.7079987 ]
Values less than 0 [-0.86027963 -2.15971501 -0.01548878 -2.09324223 -0.52046181]
[[-0.35150578  0.47868367 -1.22363779 -0.03981732  0.59581813]
 [-0.17252334  0.61139328  0.91441122  0.11865382 -1.42365947]
 [-0.89626907 -0.90011572 -0.93894539  0.11870903  1.1100425 ]
 [ 0.11495067  1.75313594  1.29981322 -0.47945582 -1.86776735]
 [-0.96778197  0.84397266  0.89068395 -0.25195623 -0.18043423]]
[-0.17252334  0.61139328  0.91441122  0.11865382 -1.42365947]
0.9144112163425275
0.9144112163425275
[[ 0.47868367 -1.22363779]
 [ 0.61139328  0.91441122]]
Values greater than 0 [0.47868367 0.59581813 0.61139328 0.91441122 0.11865382 0.11870903
 1

**Using np.random.randint function**

* The np.random.randint returns a random numpy array whose element(s) are drawn randomly from low (inclusive) to the high (exclusive) range.

* **Syntax** - np.random.randint(low, high, size)

  * low – It represents the lowest inclusive bound of the distribution from where the sample can be drawn.
  * high – It represents the upper exclusive bound of the distribution from where the sample can be drawn.
  * size – It represents the shape of the output.

##2.7 Modifying Entries of a NumPy Array

In [13]:
print(rand_mat3)

print('Matrix before modification: \n', rand_mat3)
rand_mat3[1:3,3:5]=0
print('Matrix after modification: \n', rand_mat3)


#extracting the first two rows and first 3 columns from the matrix
sub_mat=rand_mat[0:2,0:3]
print (sub_mat)

#changing all the vlues of the extracted matrix to 3
sub_mat[:] = 3
print (sub_mat)

rand_mat
 # so not just submat changes, but randmat also changes so we need to use the.copy() method when we assign submat in the future

rand_mat=np.random.randn(5,5)
print(rand_mat)
sub_mat = rand_mat[0:2,0:3].copy()
sub_mat [:] =3
print(sub_mat)
print(rand_mat)

matrix = np.arange(1,10).reshape(3,3)
matrix[0:2,1:2] = 0
print(matrix)



[[6 1 3 3 2]
 [8 6 4 5 3]
 [8 2 9 9 4]
 [3 6 9 1 4]
 [5 8 6 9 6]]
Matrix before modification: 
 [[6 1 3 3 2]
 [8 6 4 5 3]
 [8 2 9 9 4]
 [3 6 9 1 4]
 [5 8 6 9 6]]
Matrix after modification: 
 [[6 1 3 3 2]
 [8 6 4 0 0]
 [8 2 9 0 0]
 [3 6 9 1 4]
 [5 8 6 9 6]]
[[-0.35150578  0.47868367 -1.22363779]
 [-0.17252334  0.61139328  0.91441122]]
[[3. 3. 3.]
 [3. 3. 3.]]
[[ 0.61641262  0.721469    1.27641002  0.73468699  0.2277246 ]
 [ 0.22794795  1.2668607  -1.39537658 -0.67450524 -0.09172355]
 [ 0.58902977  1.91098734  2.5059854   0.36591259 -0.91361447]
 [-0.16907843  0.86809585 -0.01091478 -0.67023255  0.6783107 ]
 [ 1.87582802 -0.98629318  0.46547129 -0.24578659  0.25184691]]
[[3. 3. 3.]
 [3. 3. 3.]]
[[ 0.61641262  0.721469    1.27641002  0.73468699  0.2277246 ]
 [ 0.22794795  1.2668607  -1.39537658 -0.67450524 -0.09172355]
 [ 0.58902977  1.91098734  2.5059854   0.36591259 -0.91361447]
 [-0.16907843  0.86809585 -0.01091478 -0.67023255  0.6783107 ]
 [ 1.87582802 -0.98629318  0.46547129 -0.24578

##2.8 Saving and Loading A NumPy Array

In [14]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [41]:
randint_matrix=np.random.randint(1,10,10).reshape(2,5)
print(randint_matrix)

randint_matrix2=np.random.randint(10,20,10).reshape(2,5)
print(randint_matrix2)


np.save('/content/drive/MyDrive/saved_file_name', randint_matrix) # don't forget to get my drive in there.

#using np.savez()  we can store a file basically in a zip format.
np.savez('/content/drive/MyDrive/multiple_files',  randint_matrix= randint_matrix, randint_matrix2=randint_matrix2)

loaded_arr= np.load('/content/drive/MyDrive/saved_file_name.npy')
loaded_multi=np.load('/content/drive/MyDrive/multiple_files.npz')

print(loaded_arr)
print('')
print(loaded_multi)

# loading the values in a file
print('first matrix:\n',loaded_multi['randint_matrix'])
print('2nd matrix:\n',loaded_multi['randint_matrix2'])

new_matrix= loaded_multi['randint_matrix']
print('new matrix: \n', new_matrix)
#rand_mat_txt=np.load()


np.savetxt('/content/drive/MyDrive/text_file_name.txt', randint_matrix, delimiter=',')
rand_mat_txt=np.loadtxt('/content/drive/MyDrive/text_file_name.txt', delimiter=',')
print(randint_matrix)
print('')
print(rand_mat_txt)


[[2 4 7 1 7]
 [8 5 5 4 7]]
[[18 16 13 13 11]
 [13 19 12 12 12]]
[[2 4 7 1 7]
 [8 5 5 4 7]]

NpzFile '/content/drive/MyDrive/multiple_files.npz' with keys: randint_matrix, randint_matrix2
first matrix:
 [[2 4 7 1 7]
 [8 5 5 4 7]]
2nd matrix:
 [[18 16 13 13 11]
 [13 19 12 12 12]]
new matrix: 
 [[2 4 7 1 7]
 [8 5 5 4 7]]
[[2 4 7 1 7]
 [8 5 5 4 7]]

[[2. 4. 7. 1. 7.]
 [8. 5. 5. 4. 7.]]


##2.9 Series and DataFrames


In [42]:
import numpy as np
import pandas as pd




Pandas is a library used to create datatypes and to manipulate datatypes.
A panda series is a 1D labeled array/list capable of holding data of any type.
The labels are collectibley called index
panda sereies can be imagined as a column on an excel spreadsheet.



In [43]:
#create a list of medicine prices
med_price_list = [55,25,75,40,90]

#converting th med price list to an array
medprice= np.array(med_price_list )

#convert to a series
series_list = pd.Series(med_price_list)
series_arr =pd.Series(medprice)

#print to display
print(series_arr)
print(series_list)

#Change the index of a series
med_price_list_labeled= pd.Series(med_price_list, index = ['Omeprazole', 'Lexapro', 'Ibuprofen', 'Acetominaphen', 'Metformin'])
print(med_price_list_labeled)

#Updating prices for ***inflationnnnn**
med_price_list_updated=med_price_list_labeled + 2.5
print(med_price_list_updated)


#you can even compare the prices between the series
print(med_price_list_updated-med_price_list_labeled)

student = ['Mary', 'Peter', 'Susan', 'Toby', 'Anna']
df1 = pd.DataFrame(student, columns=['Student'])
df1

grades= ['B-','A+','B+','C','A-']
df2 = pd.DataFrame({'Student':student, 'Grade':grades})
df2


year= pd.Series([2012,2013,2014,2015,2016,2017,2018])
energy_consumption = pd.Series([2152, 2196, 2217, 2194, 2172, 2180, 2258])

df3 = pd.DataFrame({'Year':year, 'Energy_Consumption(Mtoe)':energy_consumption})
df3



0    55
1    25
2    75
3    40
4    90
dtype: int64
0    55
1    25
2    75
3    40
4    90
dtype: int64
Omeprazole       55
Lexapro          25
Ibuprofen        75
Acetominaphen    40
Metformin        90
dtype: int64
Omeprazole       57.5
Lexapro          27.5
Ibuprofen        77.5
Acetominaphen    42.5
Metformin        92.5
dtype: float64
Omeprazole       2.5
Lexapro          2.5
Ibuprofen        2.5
Acetominaphen    2.5
Metformin        2.5
dtype: float64


Year  Energy_Consumption(Mtoe)
0  2012                      2152
1  2013                      2196
2  2014                      2217
3  2015                      2194
4  2016                      2172
5  2017                      2180
6  2018                      2258

##2.10 Pandas- Accessing and Modifying Series


In [44]:
operators=['AT&T', 'Verizon', 'T-Mobile', 'US Cellular']
revenue= [171.6, 128.29, 68.4, 4.04]

telecom = pd.Series(revenue, index=operators)
print(telecom)

#accessing the first element

print(telecom[0])

#accessing the first 3 elements
print(telecom[0:3]) # 0r:3

#accessing the last two elements
print(telecom[-2:])

#accessing multiple items of the array
print(telecom[[0,2,3,]])

#accessing the revenue of AT&T
print(telecom['AT&T'])
#accessing first 3 revenus of operators in the series
print(telecom[:'T-Mobile'])
#accessing various values of the series
print(telecom[['AT&T','US Cellular','Verizon']])






AT&T           171.60
Verizon        128.29
T-Mobile        68.40
US Cellular      4.04
dtype: float64
171.6
AT&T        171.60
Verizon     128.29
T-Mobile     68.40
dtype: float64
T-Mobile       68.40
US Cellular     4.04
dtype: float64
AT&T           171.60
T-Mobile        68.40
US Cellular      4.04
dtype: float64
171.6
AT&T        171.60
Verizon     128.29
T-Mobile     68.40
dtype: float64
AT&T           171.60
US Cellular      4.04
Verizon        128.29
dtype: float64


##2.11 Pandas -Accessing DataFrames

In [45]:
store_data = pd.DataFrame({'CustomerID':['CustID00','CustID01','CustID02','CustID03','CustID04'],
                           'location':['Chicago','Boston','Seattle','San Francisco','Austin'],
                           'gender': ['M','M', 'F', 'M','F'],
                           'type':['Electronics','Foods&Beverages','Foods&Beverages','Medicine','Beauty'],
                           'quantity':[1,3,4,2,1],
                           'total_bill':[100,5,125,50,80]})


print(store_data)

#accessing the first row of the data frame
print(store_data[:1])
#grabbing the panada series
print(store_data['location'])
#Grab rows at every 2 intervals, so 0,2,& 4 show up you can specify the start and stop and intervals
store_data[::2]
#accessing rows in reverse
store_data[::-1]






  CustomerID       location gender             type  quantity  total_bill
0   CustID00        Chicago      M      Electronics         1         100
1   CustID01         Boston      M  Foods&Beverages         3           5
2   CustID02        Seattle      F  Foods&Beverages         4         125
3   CustID03  San Francisco      M         Medicine         2          50
4   CustID04         Austin      F           Beauty         1          80
  CustomerID location gender         type  quantity  total_bill
0   CustID00  Chicago      M  Electronics         1         100
0          Chicago
1           Boston
2          Seattle
3    San Francisco
4           Austin
Name: location, dtype: object


CustomerID       location gender             type  quantity  total_bill
4   CustID04         Austin      F           Beauty         1          80
3   CustID03  San Francisco      M         Medicine         2          50
2   CustID02        Seattle      F  Foods&Beverages         4         125
1   CustID01         Boston      M  Foods&Beverages         3           5
0   CustID00        Chicago      M      Electronics         1         100

##2.12 Pandas- Accessing and Modifying Data Frames (Ioc & iloc)


In [46]:
# loc method is used to access rows and columns on projects
#syntax:
#dataframe.loc[row selection, column selection]

#accessisng the first index value using loc method[indexing starts from 0]
store_data.loc[1]

#1st and 4th index and columns selected
store_data.loc[[1,4],['location', 'type']]

#we could also use the iloc method. loc uses labels, but iloc just uses the index position.
store_data.iloc[[1,4],[0,2]]

print(store_data.loc[4,'type'])
store_data.loc[4,'type']= 'Electronics'


Beauty


##2.13 Pandas- Accessing and Modifying Data Frames (Condition Based Accessing )

In [47]:
#condition based indexing
store_data['quantity']>1

#where the quantity is >1

store_data.loc[store_data['quantity']>1]

#add a new column and the values
store_data['rating']=[2,5,3,4,4]
store_data

#dropping a column
#store_data.drop('CustomerID',axis=1)
#we need axis one so it knows to drop the column
store_data #as you can see the original data frame still has the custID, but it dropw while we drop a column

#store_data.drop('CustomerID',axis=1, inplace=True)
store_data


#lets create a copy of the df
new_store_data = store_data.copy()
store_data


# we can remove many columns simultaneously
new_store_data.drop(['location','rating'],axis=1, inplace = True)
print(new_store_data)

store_data
store_data.drop(1,axis=0)
store_data

store_data_new=store_data.drop(1,axis=0)
store_data_new

store_data_new.reset_index()


store_data_new.reset_index(drop=True, inplace=True)
store_data_new



  CustomerID gender             type  quantity  total_bill
0   CustID00      M      Electronics         1         100
1   CustID01      M  Foods&Beverages         3           5
2   CustID02      F  Foods&Beverages         4         125
3   CustID03      M         Medicine         2          50
4   CustID04      F      Electronics         1          80


CustomerID       location gender             type  quantity  total_bill  \
0   CustID00        Chicago      M      Electronics         1         100   
1   CustID02        Seattle      F  Foods&Beverages         4         125   
2   CustID03  San Francisco      M         Medicine         2          50   
3   CustID04         Austin      F      Electronics         1          80   

   rating  
0       2  
1       3  
2       4  
3       4

##2.14 Pandas- Combining Data Frames


In [48]:
#how to combine data frames (using concat, join, and merge)

data_cust=pd.DataFrame({'CustomerID': ['101','102','103','104'],
                        'category':['Medium','Medium','High', 'Low'],
                        'first_visit':['yes','no','yes', 'yes'],
                        'sales':[123,52,214,663]},index=[0,1,2,3])

data_cust_new= pd.DataFrame({"CustomerID":['101','103','104','105'],
                             'distance':[12,9,44,21],
                             'sales':[123,214,663,331]},index = [4,5,6,7])
print(data_cust)
print(data_cust_new)


  CustomerID category first_visit  sales
0        101   Medium         yes    123
1        102   Medium          no     52
2        103     High         yes    214
3        104      Low         yes    663
  CustomerID  distance  sales
4        101        12    123
5        103         9    214
6        104        44    663
7        105        21    331


In [49]:
pd.concat([data_cust,data_cust_new], axis=0)# references rows

CustomerID category first_visit  sales  distance
0        101   Medium         yes    123       NaN
1        102   Medium          no     52       NaN
2        103     High         yes    214       NaN
3        104      Low         yes    663       NaN
4        101      NaN         NaN    123      12.0
5        103      NaN         NaN    214       9.0
6        104      NaN         NaN    663      44.0
7        105      NaN         NaN    331      21.0

In [50]:
pd.concat([data_cust,data_cust_new], axis=1)

CustomerID category first_visit  sales CustomerID  distance  sales
0        101   Medium         yes  123.0        NaN       NaN    NaN
1        102   Medium          no   52.0        NaN       NaN    NaN
2        103     High         yes  214.0        NaN       NaN    NaN
3        104      Low         yes  663.0        NaN       NaN    NaN
4        NaN      NaN         NaN    NaN        101      12.0  123.0
5        NaN      NaN         NaN    NaN        103       9.0  214.0
6        NaN      NaN         NaN    NaN        104      44.0  663.0
7        NaN      NaN         NaN    NaN        105      21.0  331.0

In [25]:
#merges using common values
pd.merge(data_cust, data_cust_new, how='outer', on='CustomerID')

CustomerID category first_visit  sales_x  distance  sales_y
0        101   Medium         yes    123.0      12.0    123.0
1        102   Medium          no     52.0       NaN      NaN
2        103     High         yes    214.0       9.0    214.0
3        104      Low         yes    663.0      44.0    663.0
4        105      NaN         NaN      NaN      21.0    331.0

In [51]:
pd.merge(data_cust, data_cust_new, how='inner', on='CustomerID')

CustomerID category first_visit  sales_x  distance  sales_y
0        101   Medium         yes      123        12      123
1        103     High         yes      214         9      214
2        104      Low         yes      663        44      663

In [52]:
pd.merge(data_cust, data_cust_new, how='right', on='CustomerID')

CustomerID category first_visit  sales_x  distance  sales_y
0        101   Medium         yes    123.0        12      123
1        103     High         yes    214.0         9      214
2        104      Low         yes    663.0        44      663
3        105      NaN         NaN      NaN        21      331

In [53]:
data_quarters=pd.DataFrame({'Q1':[101,102,103],
                            'Q2':[201,202,203]},index=['I0','I1','I2'])

data_quarters_new=pd.DataFrame({'Q3':[301,302,303],
                                'Q4':[401,402,403]},index=['I0','I1','I3'])
print(data_quarters)
print(data_quarters_new)

data_quarters.join(data_quarters_new, how='right') #outer, inner, left and right work the same as merge

     Q1   Q2
I0  101  201
I1  102  202
I2  103  203
     Q3   Q4
I0  301  401
I1  302  402
I3  303  403


Q1     Q2   Q3   Q4
I0  101.0  201.0  301  401
I1  102.0  202.0  302  402
I3    NaN    NaN  303  403

##2.15 Pandas- Saving and Loading Datasets

In [54]:
#from google.colab import drive
#drive.mount('/content/drive')

path="/content/drive/MyDrive/csv/StockData.csv" # we don't have this file in google drive so it won't work
data=pd.read_csv(path)
data.head #gets the first 5 records of the data file

#loading an excel to python
#path_excel="/content/drive/MyDrive/StockData.xlsx"
#data_Excel=pd.read_excel(path_excel)

#saving a file to a csv
data.to_csv('/content/drive/MyDrive/Saved_StockData.csv',index=False)
#index=false is to not have it create more index values

#saving a data set as an excel
#data.to_excel('/content/drive/MyDrive/Saved_StockData.xlsx',index=False)




##2.16 Pandas Function

In [55]:
data.head()#shows first 5 records of a data set
data.tail()#look at the last 5 rows

data.shape #checks the number of columns and rows in the dataset
data.info()#checks the data types of the columns
data['price'].min() #smallest price of the data set/
data['price'].max() #max price of the data set/
data['price'].mean()
data['price'].median()
data['price'].mode()

data['price'].mode()[0] #for just the value

data['stock'].unique()
#data['stock'].value_counts()
data



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5036 entries, 0 to 5035
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   stock   5036 non-null   object 
 1   date    5036 non-null   object 
 2   price   5036 non-null   float64
dtypes: float64(1), object(2)
memory usage: 118.2+ KB


stock        date    price
0     AAPL  08-02-2013  67.8542
1     AAPL  11-02-2013  68.5614
2     AAPL  12-02-2013  66.8428
3     AAPL  13-02-2013  66.7156
4     AAPL  14-02-2013  66.6556
...    ...         ...      ...
5031   ZTS  01-02-2018  77.8200
5032   ZTS  02-02-2018  76.7800
5033   ZTS  05-02-2018  73.8300
5034   ZTS  06-02-2018  73.2700
5035   ZTS  07-02-2018  73.8600

[5036 rows x 3 columns]

##2.17  Pandas Functions (groupby)

In [56]:
#group by

data.groupby(['stock'])['price'].mean()





stock
AAPL    109.066698
SNI      71.319206
TJX      66.743566
ZTS      45.098648
Name: price, dtype: float64

In [57]:
data.groupby(['stock'])['price'].median()

stock
AAPL    109.01
SNI      72.31
TJX      68.85
ZTS      45.62
Name: price, dtype: float64

In [58]:
def profit(s):
  return s + s*0.10  #increase stock price by 10

data['price'].apply(profit)
 #create a new column and add it to the table

data['newprice']=data['price'].apply(profit)
data.head()

#sort() sorts a data frame in ascending or descneding order of passed column
data.sort_values(by = 'newprice', ascending = False)

data.groupby(['stock']) ['price'].mean()

stock
AAPL    109.066698
SNI      71.319206
TJX      66.743566
ZTS      45.098648
Name: price, dtype: float64

##2.18 Pandas Functions (datetime)

In [59]:
data.info()
data.head()

#date for a new format, not its year, month, day
data['date']=pd.to_datetime(data['date'],dayfirst=True)
data.head()

data['date'].dt.strftime('%m/%d/%Y')
#2 digits for the year, lowercasey
data['date'].dt.strftime('%m-%d-%y')
data['date'].dt.year
data['date'].dt.month
data['date'].dt.day

data['date'][1]-data['date'][0]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5036 entries, 0 to 5035
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   stock     5036 non-null   object 
 1   date      5036 non-null   object 
 2   price     5036 non-null   float64
 3   newprice  5036 non-null   float64
dtypes: float64(2), object(2)
memory usage: 157.5+ KB


Timedelta('3 days 00:00:00')

##Quiz 2.1 -NumPy

In [60]:
import numpy as np
np.array([1,10,21,35,72])

np.arange(start=1, stop=10, step=1).reshape(3,3)
array_1 = np.linspace(0,20,6)
array_2 = np.arange(0,20,6)
print(array_1)
print(array_2)


mat = np.matrix([[ 1, 4, 9, 121, 144, 169],
                [ 16, 25, 36, 196, 225, 256],
                [ 49, 64, 81, 289, 324, 361]])
print(np.mean(mat))

a = np.arange(0,20)
print(a[2:7])

np.cos([0, 1, 2, 3, 4])


list_1 = [1,2,3]
list_2 = [4,5,6]
new_list = list_1 + list_2

print(new_list)

array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
new_array = array_1 + array_2
print(new_array)

mat = np.array([[1, 2, 1], [4, 5, 9],[1, 8, 9]])
mat[1] = 5
print(mat)


array_1 = np.array([1, 2, 3, 5, 8])
array_2 = np.array([0, 3, 4, 2, 1])
new_array = array_1+ array_2
final_array = new_array*array_1
print(final_array[2])


np.ones([2, 2])

#calculate the dot product
n1 = np.matrix([[121, 144, 169], [196, 225, 256], [ 289, 324, 361]])
n2 = np.matrix([[ 1, 4, 9], [ 1, 5, 4], [ 9, 4, 8]])
print(n1*n2)

[ 0.  4.  8. 12. 16. 20.]
[ 0  6 12 18]
131.66666666666666
[2 3 4 5 6]
[1, 2, 3, 4, 5, 6]
[5 7 9]
[[1 2 1]
 [5 5 5]
 [1 8 9]]
21
[[1786 1880 3017]
 [2725 2933 4712]
 [3862 4220 6785]]




##Quiz 2.2-Pandas

In [64]:
import pandas as pd
import numpy as np


path="/content/drive/MyDrive/csv/books.csv"
data=pd.read_csv(path)
data.head
data.shape
data.describe()
data.dtypes
data
data[(data['average_rating']>4) & (data['publisher']=='DAW')]

data['publisher'].value_counts()

Vintage                         143
Penguin Books                   124
Penguin Classics                 77
Mariner Books                    72
Pocket Books                     59
                               ... 
One World (UK)                    1
Coffee House Press                1
Plaza & Janés Editores  S.A.      1
F & W Publications Inc.           1
Abdo Publishing Company           1
Name: publisher, Length: 1408, dtype: int64

In [65]:
#data[data['average_rating']>4.5] && data[data['average_rating']<10]
#data[(data['average_rating']>4.5) & (data['ratings_count']<10)]

In [66]:
#data['num_pages'].mean()
#data['num_pages'].median()
#data['author']
#df_grouped = data.groupby('language_code')


#Which of the authors listed below have published books with ‘DAW’ publications and have an average_rating of greater than 4?
#How many books with more than 500 pages were published after 2010?



demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))
demo_matrix[0:3, 1:3]

import numpy as np
demo_array = np.arange(0,10)
demo_array<3
demo_array1 = np.arange(0,10)
demo_array1
demo_array1[0:7] = 5
demo_array1



flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])
flowers['daisy']





5